project_id = "yovinnkanomexkxmxmni"

[functions.translate]
verify_jwt = false

[functions.ai-content-moderation]
verify_jwt = false

[functions.ai-review-scoring]
verify_jwt = true

[functions.ai-recommendation]
verify_jwt = true
